
services:

  app:

    build: .

    container_name: cloudtasks-app

    ports:
      - "3000:3000"

    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/cloudtasks

    depends_on:
      - mongo

    restart: always

  mongo:

    image: mongo

    container_name: cloudtasks-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    restart: always

volumes:
  mongo_data: